export const ROLE_SKILLS: Record<string, string[]> = {
  "Frontend Dev": [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "TypeScript",
    "Next.js",
    "Tailwind CSS",
    "Redux / Zustand",
    "Browser APIs",
    "Testing (Jest)",
    "Performance Optimization",
    "Accessibility (A11y)",
  ],
  "Backend Dev": [
    "Node.js",
    "Express.js",
    "NestJS",
    "Python / Django",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "REST & GraphQL APIs",
    "Microservices Architecture",
    "Docker & Containers",
    "Authentication (JWT/OAuth)",
    "System Design",
  ],
  "Full Stack": [
    "React.js",
    "Next.js",
    "Node.js",
    "TypeScript",
    "Prisma / TypeORM",
    "PostgreSQL",
    "Tailwind CSS",
    "State Management",
    "API Development",
    "Cloud Deployment",
    "Git & GitHub",
    "Testing & CI/CD",
  ],
  "Data Scientist": [
    "Python",
    "R Programming",
    "SQL (Advanced)",
    "NumPy & Pandas",
    "Data Visualization (Matplotlib/Tableau)",
    "Scikit-Learn",
    "Deep Learning (PyTorch/TF)",
    "Natural Language Processing",
    "Statistics & Probability",
    "Big Data (Spark/Hadoop)",
    "MLOps",
    "Exploratory Data Analysis",
  ],
  DevOps: [
    "Linux Administration",
    "Docker & Kubernetes",
    "AWS / Azure / GCP",
    "Terraform (IaC)",
    "CI/CD Pipelines (GitHub Actions/Jenkins)",
    "Monitoring (Prometheus/Grafana)",
    "Nginx / Reverse Proxies",
    "Bash Scripting",
    "Network Security",
    "Site Reliability Engineering",
  ],
  "Mobile Developer": [
    "React Native",
    "Flutter / Dart",
    "Swift (iOS)",
    "Kotlin (Android)",
    "Mobile UI/UX Design",
    "State Management",
    "Native Modules",
    "Push Notifications",
    "App Store Deployment",
    "Offline Data Persistence",
  ],
  "AI Engineer": [
    "Generative AI (LLMs)",
    "Prompt Engineering",
    "Vector Databases (Pinecone/Chroma)",
    "LangChain / LlamaIndex",
    "Neural Networks",
    "Computer Vision",
    "Model Fine-tuning",
    "AI Ethics & Safety",
    "Python",
    "PyTorch",
  ],
  "Cybersecurity": [
    "Ethical Hacking",
    "Penetration Testing",
    "Network Security",
    "Cryptography",
    "SOC Monitoring",
    "Incident Response",
    "Cloud Security",
    "Malware Analysis",
    "Compliance (GDPR/SOC2)",
    "Identity & Access Management",
  ],
};
